apiVersion: v1
kind: Secret
metadata:
  name: my-service-secret
  namespace: my-service
type: Opaque
data:
  postgres_db_name: bXlfc2VydmljZQ== # my_service
  postgres_host: cG9zdGdyZXMubmFtZXNwYWNlX25hbWU= # postgres.namespace_name
  redis_host: cmVkaXMtZXhjaGFuZ2UtbWFzdGVyLmV4Y2hhbmdlLWRi # redis-exchange-master.namespace_name
  redis_port: NjM3OQ== #6379
